name: Skyowallet
main: fr.skyost.skyowallet.Skyowallet
description: Simple & lightweight economy plugin.
version: 0.3.5
author: Skyost
website: http://dev.bukkit.org/bukkit-plugins/skyowallet/
loadbefore: [Vault]
commands:
 skyowallet:
  description: Main command of Skyowallet's economy.
  aliases: [wallet, economy, econ, eco, money]
 bank:
  description: Main command of Skyowallet's banks.
  aliases: [ba]
permissions:
 skyowallet.admin:
  default: op
  description: Allows you to use admin features.
 skyowallet.infos:
  default: true
  description: Allows you to use /skyowallet infos.
 skyowallet.pay:
  default: true
  description: Allows you to use /skyowallet pay <amount> <player | uuid>.
 skyowallet.set:
  default: op
  description: Allows you to use /skyowallet set <amount> [player | uuid].
 skyowallet.sync:
  default: op
  description: Allows you to use /skyowallet sync.
 skyowallet.view:
  default: op
  description: Allows you to use /skyowallet view <player | uuid>.
 skyowallet.bank.addowner:
  default: true
  description: Allows yout to use /skyowallet addowner <player | uuid> [bank].
 skyowallet.bank.create:
  default: true
  description: Allows yout to use /skyowallet create <bank>.
 skyowallet.bank.delete:
  default: true
  description: Allows yout to use /skyowallet delete [bank].
 skyowallet.bank.deposit:
  default: true
  description: Allows yout to use /skyowallet deposit <amount>.
 skyowallet.bank.infos:
  default: true
  description: Allows yout to use /skyowallet infos [bank].
 skyowallet.bank.join:
  default: true
  description: Allows yout to use /skyowallet join <bank>.
 skyowallet.bank.leave:
  default: true
  description: Allows yout to use /skyowallet leave.
 skyowallet.bank.list:
  default: true
  description: Allows yout to use /skyowallet list.
 skyowallet.bank.removeowner:
  default: true
  description: Allows yout to use /skyowallet removeowner <player | uuid> [bank].
 skyowallet.bank.withdraw:
  default: true
  description: Allows yout to use /skyowallet withdraw <amount>.