name: ${project.name}
main: fr.skyost.skyowallet.Skyowallet
description: ${project.description}
version: ${project.version}
author: Skyost
website: http://dev.bukkit.org/bukkit-plugins/skyowallet/
loadbefore: [Vault]
commands:
 skyowallet:
  description: Main command of Skyowallet's economy.
  aliases: [wallet, economy, econ, eco, money]
 bank:
  description: Main command of Skyowallet's banks.
  aliases: [ba]
 bounty:
  description: This command is set for the Bounties extension.
  aliases: [bounties]
permissions:
 skyowallet.admin:
  default: op
  description: Allows you to use admin features.
 skyowallet.infos:
  default: true
  description: Allows you to use /skyowallet infos.
 skyowallet.pay:
  default: true
  description: Allows you to use /skyowallet pay <amount> <player | uuid>.
 skyowallet.set:
  default: op
  description: Allows you to use /skyowallet set <amount> [player | uuid].
 skyowallet.sync:
  default: op
  description: Allows you to use /skyowallet sync.
 skyowallet.view:
  default: op
  description: Allows you to use /skyowallet view <player | uuid>.
 skyowallet.bank.addowner:
  default: true
  description: Allows you to use /bank addowner <player | uuid> [bank].
 skyowallet.bank.approve:
  default: true
  description: Allows you to use /bank approve [player | uuid].
 skyowallet.bank.cancel:
  default: true
  description: Allows you to use /bank cancel.
 skyowallet.bank.create:
  default: true
  description: Allows you to use /bank create <bank>.
 skyowallet.bank.delete:
  default: true
  description: Allows you to use /bank delete [bank].
 skyowallet.bank.deny:
  default: true
  description: Allows you to use /bank deny [player | uuid] [reason].
 skyowallet.bank.deposit:
  default: true
  description: Allows you to use /bank deposit <amount>.
 skyowallet.bank.infos:
  default: true
  description: Allows you to use /bank infos [bank].
 skyowallet.bank.join:
  default: true
  description: Allows you to use /bank join <bank>.
 skyowallet.bank.leave:
  default: true
  description: Allows you to use /bank leave.
 skyowallet.bank.list:
  default: true
  description: Allows you to use /bank list.
 skyowallet.bank.removeowner:
  default: true
  description: Allows you to use /bank removeowner <player | uuid> [bank].
 skyowallet.bank.toggleapprovalneeded:
  default: true
  description: Allows you to use /bank toggleapprovalneeded [bank].
 skyowallet.bank.withdraw:
  default: true
  description: Allows you to use /bank withdraw <amount>.